
name: Clean

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Clean
    runs-on: self-hosted
    permissions: write-all
    steps:
      - name: Clean the workspace
        uses: docker://alpine
        with:
            args: /bin/sh -c "find \"${GITHUB_WORKSPACE}\" -mindepth 1 ! -name . -prune -exec rm -rf {} +"
